# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-EQdJ2FtqviU9hZ9d7WdNPOhkB1ZL35
"""


from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    'jinaai/jina-reranker-v1-turbo-en', num_labels=1, trust_remote_code=True
)

# Example query and documents
#query = "Create a 3d model of an aeroplane"
documents = [
    "a model in 3D",
    "a texture",
]

documentsForImage = [
    "Increase resolution, Upscale, Resolution, Quality",
    "Generate"
]


def correctPromptImage(query):
    sentence_pairs = [[query,doc] for doc in documentsForImage]
    scores = model.compute_score(sentence_pairs)
    print(sentence_pairs[scores.index(max(scores))][1])
    return scores.index(max(scores))

def correctPromptText(query):
    sentence_pairs = [[query, doc] for doc in documents]

    scores = model.compute_score(sentence_pairs)
    print(sentence_pairs[scores.index(max(scores))][1])
    return scores.index(max(scores))

# construct sentence pairs


# print("Original statement:\t"+sentence_pairs[0][0])

# print("Most relevant document:\t"+ str(max(scores)) )